# Base configs
baseurl: ""
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Kiara Fenco Photography"
subtitle: "Capturing moments, one frame at a time."
author: "Designed by Designify"
header:
 title: "Kiara Fenco"
 subtitle: "Stories in every shot"
footer:
 name: "Hi, I'm Kiara"
 bio: "I’m a Communication and Audiovisual student from Peru with a deep passion for photography. Through my lens, I capture the beauty of the world and tell stories that inspire."
 github: "Interested in a website like this? Check out <a href=\"https://designify.com/\">Designify</a> and bring your vision to life!"
 web_design: "Website designed by Designify"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  twitter: "https://www.twitter.com/kiarapaao/"
  instagram: "https://www.instagram.com/kiarapaao/"
  dribbble: "https://dribbble.com/kiarapaao/"
  linkedin: "https://in.linkedin.com/in/kiarapaao/" 
